build passed, segfault appear

diff --git a/solver b/solver
--- a/solver
+++ b/solver
@@ -1,8 +1,13 @@
 #!/bin/bash
 
+mkdir -p build
 cd build
-if [ ! $# -eq 1 ];then
-    echo "Provide only -b OR -r keys"
+
+if [ $# -ne 1 ];then
+    echo "ERROR: Invalid number of arguments"
+    echo "INFO: Provide -g argument to generate build files"
+    echo "-b to build the project or"
+    echo "-r to run the solver-rc executable"
     exit 1
 fi
 
@@ -14,9 +19,10 @@ then
     cmake --build .
 elif [ $1 = "-r" ];
 then
-    ./solver-rc/solver-rc;
+    ./src/solver-rc;
 else
-    exit 1
+    exit 2
 fi
 
 cd - > /dev/null
+exit 0
